### ISSUE TITLE
[MC VERSION] EssentialsX和residence领地两个插件失效

### ISSUE THREAD

**Issue by Leoparking** [MohistMC/Mohist#3217]
### 服务器今天出现了两个新的错误
[10:22:58 INFO]: The_Leopard_King issued server command: /tp 0 99 0
[10:23:13 ERROR]: Exception when The_Leopard_King attempted to tab complete tp
org.bukkit.command.CommandException: Unhandled exception during tab completion f
or command '/tp ' in plugin Essentials v2.21.0-dev+56-1929d41
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:151)
~[forge-1.20.1-47.3.4-universal.jar%23239!/:?]
        at org.bukkit.command.Command.tabComplete(Command.java:92) ~[forge-1.20.
1-47.3.4-universal.jar%23239!/:?]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java
:226) ~[forge-1.20.1-47.3.4-universal.jar%23239!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.tabCompleteCommand(CraftS
erver.java:2022) ~[forge-1.20.1-47.3.4-universal.jar%23239!/:997de31d-ddc9a2dad-
d2eba2c8-47.1.105]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.tabComplete(CraftServer.j
ava:1995) ~[forge-1.20.1-47.3.4-universal.jar%23239!/:997de31d-ddc9a2dad-d2eba2c
8-47.1.105]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.getSugge
stions(BukkitCommandWrapper.java:61) ~[forge-1.20.1-47.3.4-universal.jar%23239!/
:?]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(Argumen
tCommandNode.java:71) ~[brigadier-1.20.1.jar%23146!/:?]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(Comma
ndDispatcher.java:599) ~[brigadier-1.20.1.jar%23146!/:?]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(Comma
ndDispatcher.java:581) ~[brigadier-1.20.1.jar%23146!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$hand
leCustomCommandSuggestions$4(ServerGamePacketListenerImpl.java:761) ~[server-1.2
0.1-20230612.114412-srg.jar%23234!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-2
0230612.114412-srg.jar%23234!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLo
op.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23234!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(Reentra
ntBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23234!/:?]

        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:102
9) ~[server-1.20.1-20230612.114412-srg.jar%23234!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:173
) ~[server-1.20.1-20230612.114412-srg.jar%23234!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLo
op.java:124) ~[server-1.20.1-20230612.114412-srg.jar%23234!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1
012) ~[server-1.20.1-20230612.114412-srg.jar%23234!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:100
6) ~[server-1.20.1-20230612.114412-srg.jar%23234!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventL
oop.java:134) ~[server-1.20.1-20230612.114412-srg.jar%23234!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:9
92) ~[server-1.20.1-20230612.114412-srg.jar%23234!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:9
08) ~[server-1.20.1-20230612.114412-srg.jar%23234!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:2
81) ~[server-1.20.1-20230612.114412-srg.jar%23234!/:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/earth2me/essentials/AlternativeCo
mmandsHandler
        at com.earth2me.essentials.Essentials.onTabCompleteEssentials(Essentials
.java:689) ~[?:?]
        at com.earth2me.essentials.Essentials.onTabComplete(Essentials.java:680)
 ~[?:?]
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:142)
~[forge-1.20.1-47.3.4-universal.jar%23239!/:?]
        ... 22 more
Caused by: java.lang.ClassNotFoundException: com.earth2me.essentials.Alternative
CommandsHandler
        at com.earth2me.essentials.Essentials.onTabCompleteEssentials(Essentials
.java:689) ~[?:?]
        at com.earth2me.essentials.Essentials.onTabComplete(Essentials.java:680)
 ~[?:?]
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:142)
~[forge-1.20.1-47.3.4-universal.jar%23239!/:?]
        ... 22 more
[10:23:28 INFO]: blandtea8985加入了游戏
[10:23:28 INFO]: Player blandtea8985 ServerPlayer['blandtea8985'/5358, l='Server
Level[world]', x=0.72, y=81.00, z=0.52](blandtea8985 at 0.7190401406301354,81.0,
0.5242781292017725) logged in and will be protected for 90 secs.
[10:23:28 INFO]: blandtea8985[/124.127.144.5:57720] logged in with entity id 535
8 at ([world]0.7190401406301354, 81.0, 0.5242781292017725)
[10:23:28 ERROR]: [AnimatedScoreboard] PlaceholderAPI caused an error while pars
ing line "&e&l游戏币: ￥&r&f%vault_eco_balance%" for blandtea8985. This is not a
n issue with AnimatedScoreboard and should instead be fixed by the maintainer of
 the placeholder pack you are trying to use.
[10:23:28 WARN]:        at com.earth2me.essentials.api.Economy.getUserByName(Eco
nomy.java:78)
[10:23:28 WARN]:        at com.earth2me.essentials.api.Economy.getMoneyExact(Eco
nomy.java:145)
[10:23:28 WARN]:        at com.earth2me.essentials.api.Economy.getMoney(Economy.
java:127)
[10:23:28 WARN]:        at net.milkbowl.vault.economy.plugins.Economy_Essentials
.getBalance(Economy_Essentials.java:79)
[10:23:28 WARN]:        at net.milkbowl.vault.economy.AbstractEconomy.getBalance
(AbstractEconomy.java:22)
[10:23:28 WARN]:        at at.helpch.placeholderapi.expansion.vault.EconomyHook.
getBalance(EconomyHook.java:38)
[10:23:28 WARN]:        at at.helpch.placeholderapi.expansion.vault.EconomyHook.
onRequest(EconomyHook.java:101)
[10:23:28 WARN]:        at at.helpch.placeholderapi.expansion.vault.VaultExpansi
on.onRequest(VaultExpansion.java:69)
[10:23:28 WARN]:        at me.clip.placeholderapi.replacer.CharsReplacer.apply(C
harsReplacer.java:119)
[10:23:28 WARN]:        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders
(PlaceholderAPI.java:71)
[10:23:28 WARN]:        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders
(PlaceholderAPI.java:99)
[10:23:28 WARN]:        at me.jasperjh.animatedscoreboard.core.PlaceholderHandle
r.replacePlaceholderAPI(PlaceholderHandler.java:67)
[10:23:28 WARN]:        at me.jasperjh.animatedscoreboard.core.PlaceholderHandle
r.replaceBoth(PlaceholderHandler.java:61)
[10:23:28 WARN]:        at me.jasperjh.animatedscoreboard.core.PlaceholderHandle
r.replacePlaceholdersThrows(PlaceholderHandler.java:37)
[10:23:28 WARN]:        at me.jasperjh.animatedscoreboard.objects.PlayerScoreboa
rdLine.update(PlayerScoreboardLine.java:125)
[10:23:28 WARN]:        at me.jasperjh.animatedscoreboard.objects.PlayerScoreboa
rd.forceUpdate(PlayerScoreboard.java:153)
[10:23:28 WARN]:        at me.jasperjh.animatedscoreboard.objects.PlayerScoreboa
rd.registerTeams(PlayerScoreboard.java:197)
[10:23:28 WARN]:        at me.jasperjh.animatedscoreboard.objects.PlayerScoreboa
rd.setState(PlayerScoreboard.java:181)
[10:23:28 WARN]:        at me.jasperjh.animatedscoreboard.objects.impl.PacketImp
lementation.initialize(PacketImplementation.java:85)
[10:23:28 WARN]:        at me.jasperjh.animatedscoreboard.objects.PlayerScoreboa
rd.initialize(PlayerScoreboard.java:175)
[10:23:28 WARN]:        at me.jasperjh.animatedscoreboard.objects.ScoreboardPlay
er.tickScoreboards(ScoreboardPlayer.java:432)
[10:23:28 WARN]:        at me.jasperjh.animatedscoreboard.core.PlayerScoreboardH
andler.lambda$init$2(PlayerScoreboardHandler.java:204)
[10:23:29 INFO]: [EliteMobs] User af0a38bb-b593-390d-b7b0-83990bb3a278 data succ
essfully read!
[10:23:29 INFO]: Protected Player blandtea8985 was successful validated after 1
secs.
[10:23:29 INFO]: Removing player protection invulnerable from player blandtea898
5!

随后发现是领地插件和要点X出问题了，没有正确载入
<img width="671" alt="293d05405f8597860c37b4836a7e71ba" src="https://github.com/MohistMC/Mohist/assets/141799770/64f40397-58d0-45d2-ade2-2fba8b9c0180">

服务端版本是最新下载的mohist-1.20.1-737-server.jar且重置了libraries等资源文件

该问题在更为新的MOHIST版本中依然存在

**Comment by Leoparking** [comment]
后序：回退至695号问题依然存在？
这是怎么回事
